// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AsignaturaContext))]
    [Migration("20210702143741_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Asignatura", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Corequisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("DepartamentoOferente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HDD")
                        .HasColumnType("int");

                    b.Property<int>("HTI")
                        .HasColumnType("int");

                    b.Property<int>("HTP")
                        .HasColumnType("int");

                    b.Property<int>("HTT")
                        .HasColumnType("int");

                    b.Property<string>("Habilitable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homologable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prerequisitos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramaAcademico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Validable")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Codigo");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("Entity.Docente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreDocente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificacion");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Entity.PlanAsignatura", b =>
                {
                    b.Property<string>("CodigoPlan")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AsignaturaCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompetenciasEspecificas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetenciasGrales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metodologias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivosEspecificos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoPlan");

                    b.HasIndex("AsignaturaCodigo");

                    b.ToTable("PlanAsignaturas");
                });

            modelBuilder.Entity("Entity.PlanSolicitud", b =>
                {
                    b.Property<string>("CodigoPlanSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetenciasEspecificas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetenciasGrales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAsignatura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metodologias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivosEspecificos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoPlanSolicitud");

                    b.HasIndex("IdAsignatura");

                    b.ToTable("PlanSolicitud");
                });

            modelBuilder.Entity("Entity.PlanViejo", b =>
                {
                    b.Property<string>("CodigoPlanViejo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetenciasEspecificas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompetenciasGrales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estrategias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAsignatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metodologias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivoGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetivosEspecificos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoPlanViejo");

                    b.ToTable("PlanesViejos");
                });

            modelBuilder.Entity("Entity.Solicitud", b =>
                {
                    b.Property<string>("CodigoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanSolicitudCodigoPlanSolicitud")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoSolicitud");

                    b.HasIndex("PlanSolicitudCodigoPlanSolicitud");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Entity.PlanAsignatura", b =>
                {
                    b.HasOne("Entity.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaCodigo");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("Entity.PlanSolicitud", b =>
                {
                    b.HasOne("Entity.Asignatura", null)
                        .WithMany()
                        .HasForeignKey("IdAsignatura");
                });

            modelBuilder.Entity("Entity.Solicitud", b =>
                {
                    b.HasOne("Entity.PlanSolicitud", "PlanSolicitud")
                        .WithMany()
                        .HasForeignKey("PlanSolicitudCodigoPlanSolicitud");

                    b.Navigation("PlanSolicitud");
                });
#pragma warning restore 612, 618
        }
    }
}
